// AUTH
export const LOGIN = "LOGIN";
export const IS_LOGGED_IN = "IS_LOGGED_IN";
export const REGISTER = "REGISTER";
export const LOGOUT = "LOGOUT";
export const REQUEST_PASSWORD_RESET = "REQUEST_PASSWORD_RESET";
export const CONFIRM_PASSWORD_RESET = "CONFIRM_PASSWORD_RESET";
export const VERIFY_PASSWORD_RESET_CODE = "VERIFY_PASSWORD_RESET_CODE";

// CURRENT TIME TRACKING
export const TIME_ENTRY_INPUT__START = "TIME_ENTRY_INPUT__START";
export const TIME_ENTRY_INPUT__STOP = "TIME_ENTRY_INPUT__STOP";

// FETCHING ENTRIES
export const TIME_ENTRIES_FETCH_LIST = "TIME_ENTRIES_FETCH_LIST";
export const TIME_ENTRIES_DELETE = "TIME_ENTRIES_DELETE";
export const TIME_ENTRIES__ASSIGN_TAG = "TIME_ENTRIES__ASSIGN_TAG";
export const TIME_ENTRIES__ASSIGN_TAG_ID = "TIME_ENTRIES__ASSIGN_TAG_ID";

// NOTIFICATIONS
export const GET_NOTIFICATIONS = "NOTIFICATIONS";

// WORKSPACES
export const GET_DEFAULT_WORKSPACE = "DEFAULT_WORKSPACE";
export const GET_WORKSPACES = "WORKSPACES";
export const CHANGE_DEFAULT_WORKSPACE = "CHANGE_DEFAULT_WORKSPACE";

// REPORTS

// TAGS

// CLIENTS

// PROJECTS

// TASKS
